import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
dimensions = { columns = 110, lines = 30 }
padding = { x = 10, y = 10 }
decorations = "Buttonless"

# Font configuration
[font]
normal = { family = "JetBrainsMonoNL Nerd Font", style = "Regular" }
size = 13.0
offset = { x = 2, y = 0 }

